volumes:
  validate_postgres15_data: {}

services:
  # Infrastructure dependencies
  postgres:
    image: postgres:15
    container_name: v_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 999
    volumes:
      - type: volume
        source: validate_postgres15_data
        target: /var/lib/postgresql/data
    env_file:
      - ../local/env/common
    ports:
      - "18100:5432"

  # Application services
  jupyter:
    extends:
      file: base.yml
      service: base
    image: validate/jupyter
    build:
      context: ../..
      dockerfile: ./devops/local/jupyter.dockerfile
    container_name: v_jupyter
    ports:
      - "18000:8888"

  next:
    extends:
      file: base.yml
      service: base
    image: validate/next
    build:
      context: ../..
      dockerfile: ./devops/local/next.dockerfile
    container_name: v_next
    ports:
      - "18001:3000"
